[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]


[target.riscv32imac-unknown-none-elf]
runner = """\
    qemu-system-riscv32 \
        -machine virt \
        -cpu rv32 \
        -smp 32 \
        -m 64M \
        -nographic \
        -serial mon:stdio \
        -bios none \
        -kernel
"""

